import socket
import os
import sys
sys.path.append(config['git_dir'])
from utils.utils import *
import pandas as pd

RES_FOLDER = config["output_dir"]
LOG_PATH=os.path.join(RES_FOLDER, config['run'], "logs/")

include: f"{config['git_dir']}/workflow/rules/preprocessing.snk"
include: f"{config['git_dir']}/workflow/rules/qc.snk"
include: f"{config['git_dir']}/workflow/rules/common.snk"
include: f"{config['git_dir']}/workflow/rules/sv_calling.snk"
include: f"{config['git_dir']}/workflow/rules/snv_calling.snk"
include: f"{config['git_dir']}/workflow/rules/cnv.snk"
include: f"{config['git_dir']}/workflow/rules/circos.snk"


# target rules
rule all:
    input:
        getOutputs(config["analysis"], RES_FOLDER, config["samples"], config["run"])